backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: docs/uploads
media_library:
  name: uploads

collections:
  - name: "reportlab"
    label: "ReportLab User Guide"
    folder: "docs/reportlab"